Very rough prototype
iamReinir/AzureTank pull request #16
Opened 2024-05-26 08:39 UTC by iamReinir

2024-05-27 04:15 UTC, CanhTruongKool requested changes
Góp ý trước khi merge nhánh Trung vào main:
-Sửa cái xoay tank khi bấm di chuột: chỉ xoay gun không xoay tank, tank chỉ có 4 hướng : khi bấm ASWD thì xoay tank qua hướng đó (đổi model sang hình chữ nhật cho dễ apply). Enemy thì để hình tròn cũng đc.
-Thêm cái khung back ground được không? để giới hạn vùng chơi, dễ apply back ground cho khu vực chơi.

2024-05-27 07:19 UTC, iamReinir commented
Commit trên đã apply phần @CanhTruongKool  đã feedback nha, nhờ Cảnh check lại

2024-05-27 08:25 UTC, CanhTruongKool approved these changes

2024-05-27 08:26 UTC, iamReinir commented
nhờ @Dungnguyengl review cái này

2024-05-27 11:08 UTC, Dungnguyengl commented
Code init hẻ change nhìu dị

2024-05-27 12:14 UTC, iamReinir commented
code prototype á @Dungnguyengl , ko phải code init đâu

2024-05-27 12:27 UTC, Dungnguyengl commented
để review phát nhé h mới đụng vào máy tính

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/Ultility.cs
> +        public const KeyCode down = KeyCode.S;
clean code 1 xí thì constant nên in hoa

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/Ultility.cs
> +﻿using System;
được thì nên bỏ bớt thư viện không dùng

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/Ultility.cs
> +    public static class Key
không cần thiết phải đặt class là static

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/BulletBehaviour.cs
> +    float live_time = 3;
Nên tách riêng thành class constant khác

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/BulletBehaviour.cs
> +    CircleCollider2D collider;
được thì những instance như này nên để read-only

2024-05-27 17:00 UTC, Dungnguyengl commented on Assets/BulletBehaviour.cs
> +public class BulletBehaviour : MonoBehaviour
thiếu access scope rồi

2024-05-27 17:01 UTC, Dungnguyengl commented
logic t thấy ok ròi nhưng cón comment về coding xí

2024-05-28 01:06 UTC, iamReinir commented on Assets/Ultility.cs
> +    public static class Key
class Key này sẽ dùng để implement config -> lúc đó sẽ bỏ static.

2024-05-28 01:07 UTC, iamReinir commented on Assets/BulletBehaviour.cs
> +    float live_time = 3;
collider thì thừa, live_time thì (dự định) có thể bị các GameObject khác đổi -> ko phải const

2024-05-28 01:07 UTC, iamReinir commented on Assets/BulletBehaviour.cs
> +    CircleCollider2D collider;
collider thừa á. Để xoá

2024-05-28 01:08 UTC, iamReinir commented on Assets/BulletBehaviour.cs
> +public class BulletBehaviour : MonoBehaviour
không hiểu cái này

2024-05-28 01:16 UTC, iamReinir commented on Assets/Ultility.cs
> +        public const KeyCode down = KeyCode.S;
done

2024-05-28 01:16 UTC, iamReinir commented on Assets/Ultility.cs
> +﻿using System;
done

2024-05-28 01:18 UTC, iamReinir commented on Assets/BulletBehaviour.cs
> +    float live_time = 3;
hầu hết các const trong class đều dự định là đổi đc, nên để trong behaviour

2024-05-28 01:37 UTC, Dungnguyengl commented
Tạm tạm ròi bữa sau bắt bẻ típ

2024-05-28 01:41 UTC, Dungnguyengl commented on Assets/BulletBehaviour.cs
> +public class BulletBehaviour : MonoBehaviour
Private public đồ á

2024-05-28 01:41 UTC, Dungnguyengl reviewed
Commented

2024-05-28 04:04 UTC, Dungnguyengl approved these changes

2024-05-28 04:05 UTC, merged