Coding/simple HP bar and a HP component -> code only
iamReinir/AzureTank pull request #36
Opened 2024-06-05 07:13 UTC by iamReinir

Thêm MonoBehaviour : Health , dự định là sẽ dùng nó để xử lí phần HP và HP bar

2024-06-05 13:46 UTC, Dungnguyengl approved these changes

2024-06-06 02:43 UTC, dongloi2504 approved these changes

2024-06-11 17:07 UTC, Dungnguyengl requested changes

2024-06-11 17:07 UTC, Dungnguyengl commented on Assets/Health.cs
> +    public int health;
nên tạo class Health chứa những property và method liên quan đến heath và sửa class này thành Behaviour
T  đang hình dung các class Behaviour là để xử lý code behind của của các object trên UI. Không biết phải không

2024-06-12 00:30 UTC, iamReinir commented on Assets/Health.cs
> +    public int health;
các class Behaviour thì hoạt động giống một component, nó thay đổi behaviour của gameObject khi được thêm vào á. Một behaviour dùng cho nhiều gameObject được và một gameObject có thể có nhiều behaviour. Để nó ở riêng ra thì lúc lôi nó bỏ vào object khác thì phải kéo cái còn lại theo.

2024-06-12 06:51 UTC, Dungnguyengl approved these changes

2024-06-13 03:21 UTC, CanhTruongKool commented
@iamReinir ơi, thêm mấy cái bomb, hp, rocket cho map chứ giờ đang warning null trước khi merge. Cần merge trước cuối tuần để implement new features 
![image](https://github.com/iamReinir/AzureTank/assets/120951113/10bdc2dc-e5ce-4fc4-9f72-5e3e6ceb2aac)

2024-06-15 02:06 UTC, merged