Dat intervention ( pause, end game )
iamReinir/AzureTank pull request #37
Opened 2024-06-06 03:47 UTC by Arthur-Cap

- một vài button có thể sử dụng, một vài thì chưa có các screen đích cần thiết, chưa biết dẫn đến đâu -> bỏ trống active
- chỉ số của end game như "thời gian hoàn thành màn" , enemy killed, exp , hoặc là chưa biết ở đâu, hoặc là chưa tồn tại nên còn đang fix cứng

2024-06-06 05:09 UTC, Dungnguyengl requested changes

2024-06-06 05:09 UTC, Dungnguyengl commented on Assets/EndPointBehavior.cs
> +    public void Endgame(Boolean gameResult)
Đặt tên biến là isWin cho dễ hiểu
Còn nếu để game result thì đặt type là enum

2024-06-07 09:18 UTC, Arthur-Cap commented on Assets/EndPointBehavior.cs
> +    public void Endgame(Boolean gameResult)
hợp lý , đã sửa

2024-06-07 16:28 UTC, CanhTruongKool approved these changes

2024-06-08 03:42 UTC, CanhTruongKool commented
Wtf is this speed, too fast :)

2024-06-08 03:51 UTC, CanhTruongKool commented
@Arthur-Cap  Ủa sao chết với win đều là win game vậy kìa :)
cái chỗ end-point chưa thêm đồ họa à

2024-06-08 07:12 UTC, Arthur-Cap commented
@CanhTruongKool cái speed đang có vấn đề,  tốc độ thay đổi theo cửa sổ game nên để merge cái fix delta time của Trung vào đã,  còn tui đặt speed cao cao test cho nhanh á, merge thì giữ cái cũ lại,  còn đồ họa end point đâu phải của toi đâu ,hiển thị win lost thì để update

2024-06-08 07:14 UTC, CanhTruongKool commented
> ái speed đang có vấn đề, tốc độ thay đổi theo cửa sổ game nên để merge cái fix delta time của Trung vào đã, còn tui đặt speed cao cao test cho nhanh á, merge thì giữ cái cũ lại, còn đồ họa end point đâu phải của toi đâu ,hiển thị win lost thì để update

2024-06-08 07:14 UTC, closed without merging