Dat intervention
iamReinir/AzureTank pull request #48
Opened 2024-06-11 09:30 UTC by Arthur-Cap

+ End game result title added
+ Add timecounter
+ Add time in result
- Cảnh-kun count enemy kiểu gì vào update cái result đi, tìm không ra =))

2024-06-11 16:59 UTC, Dungnguyengl requested changes
Lỗi coding quá. cần fix

2024-06-11 16:59 UTC, Dungnguyengl commented on Assets/EndGameStatic.cs
> +        timeCounter.text = TimeCounter.time;
Không gán biến nội bộ như vậy.

2024-06-11 16:59 UTC, Dungnguyengl commented on Assets/TimeCounter.cs
> +            timeCounter.text = time =   minutes + ":" + seconds;
tại sao đã gán trong nội bộ class còn gán ở ngoài như ở trên

2024-06-12 01:24 UTC, Arthur-Cap commented on Assets/EndGameStatic.cs
> +        timeCounter.text = TimeCounter.time;
oke để thêm getter

2024-06-12 01:27 UTC, Arthur-Cap commented on Assets/TimeCounter.cs
> +            timeCounter.text = time =   minutes + ":" + seconds;
vì nó là 2 biến khác nhau, 
timecounter ở duới để trong update() => chạy liên tục để hiển thị time player đã chơi lên trên màn hình.
timecounter ở trên ở trong start() và nằm trong script gắn với endgame panel => chạy 1 lần duy nhất =>  hiển thị time đã chơi tính đến lúc end game
để sửa lại tên cho khỏi nhầm lẫn

2024-06-12 06:47 UTC, Dungnguyengl commented on Assets/TimeCounter.cs
> +            timeCounter.text = time =   minutes + ":" + seconds;
Là sao nhỉ t thấy nó vẫn là thuộc tính nội bộ của time counter mà

2024-06-12 08:09 UTC, Arthur-Cap commented on Assets/TimeCounter.cs
> +            timeCounter.text = time =   minutes + ":" + seconds;
![image](https://github.com/iamReinir/AzureTank/assets/125182326/98b9f231-83a4-4da4-9c5d-b6d2f1546154)

2024-06-13 16:54 UTC, Dungnguyengl requested changes

2024-06-13 16:54 UTC, Dungnguyengl commented on Assets/EndGameStatic.cs
> +        totalPlayTime.text  = TimeCounter.GameDuration;
Vậy tại sao không gán trong method StopTimer mà phải gán ở ngoài ntn?

2024-06-13 17:21 UTC, Arthur-Cap commented on Assets/EndGameStatic.cs
> +        totalPlayTime.text  = TimeCounter.GameDuration;
Hàm StopTimer thì chỉ nên làm việc của stopTimer, sao stoptimer lại có cả gán giá trị trong đó, chưa kể stopTimer có thể sử dụng để dừng time lúc tạm dừng game, lúc đó đã endgame đâu mà set text của endgame làm gì

2024-06-13 17:36 UTC, Dungnguyengl commented on Assets/EndGameStatic.cs
> +        totalPlayTime.text  = TimeCounter.GameDuration;
Vậy sao không viết thêm 1 method để thực hiện nhiệm vụ gán cho text
mà lại lôi ra ngoài để gán ntn?

2024-06-13 17:38 UTC, Arthur-Cap commented on Assets/EndGameStatic.cs
> +        totalPlayTime.text  = TimeCounter.GameDuration;
Nên mới gán vào start()  của endgameUI để nó gán duy nhất 1 lần thôi rồi display lên

2024-06-14 05:05 UTC, Arthur-Cap commented on Assets/EndGameStatic.cs
> +        totalPlayTime.text  = TimeCounter.GameDuration;
> Vậy sao không viết thêm 1 method để thực hiện nhiệm vụ gán cho text mà lại lôi ra ngoài để gán ntn?

Hàm start()  đối với gameObject giống như constructor đối với class, nó phần lớn là để khởi tạo giá trị, thiết lập trạng thái ban đầu cho những đứa bên trong, nên việc set giá trị trong start()  hoặc trong constructor không có gì khó hiểu, hơn nữa hàm ngoài việc tường minh thì còn nên có tính sử dụng lại, và việc tạo thêm một cái hàm mà nó không tăng tính tường minh bao nhiêu, mà lại còn chỉ có sử dụng được đúng 1 lần làm code lòng thòng, không khác nào bảo constructor cũng nên có hàm gán giá trị thay vì gán trực tiếp bên trong constructor

2024-06-15 02:10 UTC, iamReinir commented
@Arthur-Cap có các màn rồi kìa, nhờ ông apply vào cái mới nha

2024-06-17 05:21 UTC, closed without merging